-- MySQL Script generated by MySQL Workbench
-- Sat Aug  2 23:35:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema boutique2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boutique2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boutique2` DEFAULT CHARACTER SET utf8mb3 ;
USE `boutique2` ;

-- -----------------------------------------------------
-- Table `boutique2`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique2`.`clientes` (
  `IdClientes` INT NOT NULL AUTO_INCREMENT,
  `NombreCli` VARCHAR(45) NOT NULL,
  `ApellidoCli` VARCHAR(50) NOT NULL,
  `DireccionCli` VARCHAR(60) NOT NULL,
  `EstadoCli` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  `TelefonoCli1` VARCHAR(10) NOT NULL,
  `TelefonoCli2` VARCHAR(10) NULL DEFAULT NULL,
  `CorreoCli1` VARCHAR(45) NOT NULL,
  `CorreoCli2` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdClientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `boutique2`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique2`.`empleados` (
  `IdEmpleados` INT NOT NULL AUTO_INCREMENT,
  `NombreEmp` VARCHAR(45) NOT NULL,
  `ApellidoEmp` VARCHAR(50) NOT NULL,
  `Puesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdEmpleados`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `boutique2`.`correosemp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique2`.`correosemp` (
  `Empleados_IdEmpleados` INT NOT NULL,
  `CorreoEmp` VARCHAR(70) NOT NULL,
  INDEX `Empleados_IdEmpleados` (`Empleados_IdEmpleados` ASC) VISIBLE,
  CONSTRAINT `correosemp_ibfk_1`
    FOREIGN KEY (`Empleados_IdEmpleados`)
    REFERENCES `boutique2`.`empleados` (`IdEmpleados`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `boutique2`.`creditos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique2`.`creditos` (
  `IdCreditos` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Inicio` DATE NOT NULL,
  `Estado` ENUM('Pendiente', 'Liquidado') NOT NULL DEFAULT 'Pendiente',
  `Numero_Cuotas` INT NOT NULL,
  `Interes` DECIMAL(5,2) NOT NULL,
  `Saldo_Pendiente` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `Total_Credito` DECIMAL(10,2) NOT NULL,
  `Clientes_IdClientes` INT NOT NULL,
  PRIMARY KEY (`IdCreditos`),
  INDEX `Clientes_IdClientes` (`Clientes_IdClientes` ASC) VISIBLE,
  CONSTRAINT `creditos_ibfk_1`
    FOREIGN KEY (`Clientes_IdClientes`)
    REFERENCES `boutique2`.`clientes` (`IdClientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `boutique2`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique2`.`facturas` (
  `IdFacturas` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  `Clientes_IdClientes` INT NOT NULL,
  `Empleados_IdEmpleados` INT NOT NULL,
  `creditos_IdCreditos` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IdFacturas`),
  INDEX `Clientes_IdClientes` (`Clientes_IdClientes` ASC) VISIBLE,
  INDEX `Empleados_IdEmpleados` (`Empleados_IdEmpleados` ASC) VISIBLE,
  INDEX `fk_facturas_creditos1_idx` (`creditos_IdCreditos` ASC) VISIBLE,
  CONSTRAINT `facturas_ibfk_1`
    FOREIGN KEY (`Clientes_IdClientes`)
    REFERENCES `boutique2`.`clientes` (`IdClientes`),
  CONSTRAINT `facturas_ibfk_2`
    FOREIGN KEY (`Empleados_IdEmpleados`)
    REFERENCES `boutique2`.`empleados` (`IdEmpleados`),
  CONSTRAINT `fk_facturas_creditos1`
    FOREIGN KEY (`creditos_IdCreditos`)
    REFERENCES `boutique2`.`creditos` (`IdCreditos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `boutique2`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique2`.`productos` (
  `IdProductos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(80) NOT NULL,
  `Precio` DECIMAL(10,2) NOT NULL,
  `Stock` INT NOT NULL,
  `Precio_Compra` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`IdProductos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `boutique2`.`detalles_facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique2`.`detalles_facturas` (
  `Facturas_IdFacturas` INT NOT NULL,
  `Productos_IdProductos` INT NOT NULL,
  `Precio_Uni` DECIMAL(10,2) NOT NULL,
  `Cantidad` INT NOT NULL,
  INDEX `Productos_IdProductos` (`Productos_IdProductos` ASC) VISIBLE,
  INDEX `detalles_facturas_ibfk_1` (`Facturas_IdFacturas` ASC) VISIBLE,
  CONSTRAINT `detalles_facturas_ibfk_1`
    FOREIGN KEY (`Facturas_IdFacturas`)
    REFERENCES `boutique2`.`facturas` (`IdFacturas`),
  CONSTRAINT `detalles_facturas_ibfk_2`
    FOREIGN KEY (`Productos_IdProductos`)
    REFERENCES `boutique2`.`productos` (`IdProductos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `boutique2`.`entrada_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique2`.`entrada_productos` (
  `IdEntrada` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Producto_Id` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio_Compra` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`IdEntrada`),
  INDEX `Producto_Id` (`Producto_Id` ASC) VISIBLE,
  CONSTRAINT `entrada_productos_ibfk_1`
    FOREIGN KEY (`Producto_Id`)
    REFERENCES `boutique2`.`productos` (`IdProductos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `boutique2`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique2`.`pagos` (
  `IdPagos` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Pago` DATE NOT NULL,
  `Monto_Pagado` DECIMAL(10,2) NOT NULL,
  `Numero_Cuota` INT NOT NULL,
  `Creditos_IdCreditos` INT NOT NULL,
  PRIMARY KEY (`IdPagos`),
  INDEX `Creditos_IdCreditos` (`Creditos_IdCreditos` ASC) VISIBLE,
  CONSTRAINT `pagos_ibfk_1`
    FOREIGN KEY (`Creditos_IdCreditos`)
    REFERENCES `boutique2`.`creditos` (`IdCreditos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `boutique2`.`telefonosemp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique2`.`telefonosemp` (
  `Empleados_IdEmpleados` INT NOT NULL,
  `TelefonoEmp` VARCHAR(15) NOT NULL,
  INDEX `Empleados_IdEmpleados` (`Empleados_IdEmpleados` ASC) VISIBLE,
  CONSTRAINT `telefonosemp_ibfk_1`
    FOREIGN KEY (`Empleados_IdEmpleados`)
    REFERENCES `boutique2`.`empleados` (`IdEmpleados`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `boutique2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique2`.`usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(255) NOT NULL,
  `empleados_IdEmpleados` INT NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  INDEX `fk_usuario_empleados1_idx` (`empleados_IdEmpleados` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empleados1`
    FOREIGN KEY (`empleados_IdEmpleados`)
    REFERENCES `boutique2`.`empleados` (`IdEmpleados`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `boutique2` ;

-- -----------------------------------------------------
-- procedure AltaClientes
-- -----------------------------------------------------

DELIMITER $$
USE `boutique2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AltaClientes`(
  IN NombreCli VARCHAR(45),
  IN ApellidoCli VARCHAR(50),
  IN DireccionCli VARCHAR(60),
  IN EstadoCli ENUM('Activo', 'Inactivo'),
  IN TelefonoCli1 VARCHAR(10),
  IN TelefonoCli2 VARCHAR(10),
  IN CorreoCli1 VARCHAR(45),
  IN CorreoCli2 VARCHAR(45)
)
BEGIN
  INSERT INTO clientes (
    NombreCli, ApellidoCli, DireccionCli, EstadoCli,
    TelefonoCli1, TelefonoCli2, CorreoCli1, CorreoCli2
  ) VALUES (
    NombreCli, ApellidoCli, DireccionCli, EstadoCli,
    TelefonoCli1, TelefonoCli2, CorreoCli1, CorreoCli2
  );
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure AltaCorreosClientes
-- -----------------------------------------------------

DELIMITER $$
USE `boutique2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AltaCorreosClientes`( IN clienteId INT,IN correo VARCHAR(70))
BEGIN
 INSERT INTO correoscli VALUES (clienteId, correo);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure AltaProductos
-- -----------------------------------------------------

DELIMITER $$
USE `boutique2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AltaProductos`( IN nombre VARCHAR(45),
    IN descripcion VARCHAR(80),
    IN precio_compra DECIMAL(10,2),
    IN stock INT
)
BEGIN
	DECLARE precio_venta DECIMAL(10,2);
    DECLARE producto_id INT;

    -- Calcular precio de venta
    SET precio_venta = ROUND(precio_compra * 1.25, 2);

    -- Insertar el nuevo producto
    INSERT INTO productos (Nombre, Descripcion, Precio, Precio_Compra, Stock)
    VALUES (nombre, descripcion, precio_venta, precio_compra, stock);

    -- Obtener el ID del producto insertado
    SET producto_id = LAST_INSERT_ID();

    -- Registrar la entrada en el historial de compras
    INSERT INTO entrada_productos (Fecha, Producto_Id, Cantidad, Precio_Compra)
    VALUES (CURRENT_DATE, producto_id, stock, precio_compra);


END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure AltaTelefonosClientes
-- -----------------------------------------------------

DELIMITER $$
USE `boutique2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AltaTelefonosClientes`(IN clienteId INT,IN telefono VARCHAR(15))
BEGIN
	INSERT INTO telefonoscli VALUES (clienteId, telefono);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure AñadirStock
-- -----------------------------------------------------

DELIMITER $$
USE `boutique2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AñadirStock`(
    IN p_producto_id INT,
    IN p_cantidad INT,
    IN p_precio_compra DECIMAL(10,2)
)
BEGIN
  DECLARE nuevo_precio_venta DECIMAL(10,2);

    -- Calcular el precio de venta con margen del 25%
    SET nuevo_precio_venta = ROUND(p_precio_compra * 1.25, 2);

    -- Registrar la entrada de inventario
    INSERT INTO entrada_productos (Fecha, Producto_Id, Cantidad, Precio_Compra)
    VALUES (CURRENT_DATE, p_producto_id, p_cantidad, p_precio_compra);

    -- Actualizar stock y precios en productos
    UPDATE productos
    SET 
        Stock = Stock + p_cantidad,
        Precio_Compra = p_precio_compra,
        Precio = nuevo_precio_venta
    WHERE IdProductos = p_producto_id;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure RegistrarVenta
-- -----------------------------------------------------

DELIMITER $$
USE `boutique2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `RegistrarVenta`(IN p_Fecha DATE,
    IN p_Total DECIMAL(10,2),
    IN p_IdCliente INT,
    IN p_IdEmpleado INT
)
BEGIN
DECLARE v_IdFactura INT;

    -- Insertar en la tabla de facturas (por ahora, tipo fijo: Contado)
    INSERT INTO facturas (Fecha, Total, Clientes_IdClientes, Empleados_IdEmpleados)
    VALUES (p_Fecha, p_Total, p_IdCliente, p_IdEmpleado);

    -- Obtener el ID generado automáticamente
    SET v_IdFactura = LAST_INSERT_ID();

    -- Retorna el ID si lo necesitas (opcional)
    SELECT v_IdFactura AS IdFacturaGenerada;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- function comprobar_cliente_registrado
-- -----------------------------------------------------

DELIMITER $$
USE `boutique2`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `comprobar_cliente_registrado`(
    id_cliente INT
) RETURNS tinyint(1)
    READS SQL DATA
BEGIN
    DECLARE cliente_existe INT;

    -- Contar cuántos clientes existen con el ID proporcionado
    SELECT COUNT(*) INTO cliente_existe 
    FROM `boutique2`.`clientes` 
    WHERE IdClientes = id_cliente;

    -- Si el conteo es mayor a 0, el cliente existe
    IF cliente_existe > 0 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function validar_producto_registrado
-- -----------------------------------------------------

DELIMITER $$
USE `boutique2`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `validar_producto_registrado`(
    id_producto INT
) RETURNS tinyint(1)
    READS SQL DATA
BEGIN
    DECLARE producto_existe INT;

    -- Contar cuántos productos existen con el ID proporcionado
    SELECT COUNT(*) INTO producto_existe 
    FROM `boutique2`.`productos` 
    WHERE IdProductos = id_producto;

    -- Si el conteo es mayor a 0, el producto existe
    IF producto_existe > 0 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function verificar_stock_disponible
-- -----------------------------------------------------

DELIMITER $$
USE `boutique2`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `verificar_stock_disponible`(
    id_producto INT, 
    cantidad INT
) RETURNS tinyint(1)
    READS SQL DATA
BEGIN
    DECLARE stock_actual INT;

    -- Obtener el stock actual del producto
    SELECT Stock INTO stock_actual 
    FROM `boutique2`.`productos` 
    WHERE IdProductos = id_producto;

    -- Comprobar si el stock es suficiente
    IF stock_actual >= cantidad THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END$$

DELIMITER ;
USE `boutique2`;

DELIMITER $$
USE `boutique2`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `boutique2`.`disminuir_stock`
AFTER INSERT ON `boutique2`.`detalles_facturas`
FOR EACH ROW
BEGIN
    UPDATE productos SET Stock = Stock - NEW.Cantidad
    WHERE IdProductos = NEW.Productos_IdProductos;
END$$

USE `boutique2`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `boutique2`.`ActualizarEstado`
AFTER INSERT ON `boutique2`.`pagos`
FOR EACH ROW
BEGIN
  UPDATE creditos
  SET Estado = 'Liquidado'
  WHERE IdCreditos = NEW.Creditos_IdCreditos
    AND Saldo_Pendiente = 0;
END$$

USE `boutique2`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `boutique2`.`ActualizarSaldo`
AFTER INSERT ON `boutique2`.`pagos`
FOR EACH ROW
BEGIN
    UPDATE creditos
    SET Saldo_Pendiente = Saldo_Pendiente - NEW.Monto_Pagado
    WHERE IdCreditos = NEW.Creditos_IdCreditos;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
insert empleados values (default,'Karely','Aragon','Administrador');
insert empleados values (default,'Julian','Arciniega','Cajero');
insert empleados values (default,'Emiliano','Lopez','Almacenista');
insert usuario values (default,'Administrador','Administrador','123456',1);
insert usuario values (default,'Cajero','Cajero','123456',2);
insert usuario values (default,'Almacenista','Almacenista','123456',3);